"""Crawl Agent's output (raw pages) -> CompanyProfile. One LLM call per
company (two if the first one looks suspiciously empty).

Testing against real sites surfaced two real failure modes, both fixed here
rather than papered over:
1. Given a Basecamp pricing page with unambiguous, clearly-formatted pricing
   text, the model once returned an entirely empty profile while
   self-reporting "high" confidence.
2. When `missing_fields` was a model-generated field (even after constraining
   its allowed values to an enum), the model got stuck in a degenerate loop
   repeating a single valid value hundreds of times — a classic
   schema-constrained-decoding failure mode — burning the entire output
   budget on a field the model was never in a position to judge accurately.

Fix for both: `extraction_confidence` and `missing_fields` are never
generated by the LLM at all. The LLM only fills in the fields it can
actually judge from the text (`_ExtractionResult` below); the two
meta-fields are always computed in code from what actually came back."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, Field

from ..llm import LLMClient
from ..schemas import CompanyProfile, MissingField, PricingTier

_SYSTEM_PROMPT = """You are a meticulous competitive-intelligence analyst.

Extract structured company information STRICTLY from the page content provided.
Rules:
- Do not use outside knowledge of the company. Only use what's in the text below.
- The text below is real content from the company's own site — if it mentions
  pricing, plans, or features anywhere, extract them. Do not return an empty
  result when the source text clearly contains this information.
- Never invent a plausible-sounding value that isn't actually in the text.
- For pricing, capture tiers exactly as displayed (name, price string, billing
  period, and the bullet points of what's included).
- Leave a field null/empty if the text genuinely doesn't cover it. Do not
  explain why a field is missing — just leave it empty.
"""

_RETRY_SUFFIX = """

IMPORTANT: your previous attempt on this exact content returned an empty
result (no pricing, no features, no value proposition), but the page text
below does contain real company information. Read it again carefully and
extract what is actually there — do not return an empty result again unless
the text truly contains nothing relevant."""

_MAX_CHARS_PER_PAGE = 6000  # keep the prompt within a reasonable context budget


class _ExtractionResult(BaseModel):
    """What the LLM is actually asked to produce — deliberately just the
    substantive fields it can judge from the text. No confidence, no
    missing-fields self-report: see module docstring for why."""

    company_name: str | None = None
    value_proposition: str | None = None
    target_icp: str | None = None
    pricing_tiers: list[PricingTier] = Field(default_factory=list)
    features: list[str] = Field(default_factory=list)


def _build_prompt(domain: str, pages: dict[str, str], retry: bool = False) -> str:
    sections = [f"Domain being analyzed: {domain}\n"]
    for url, markdown in pages.items():
        truncated = markdown[:_MAX_CHARS_PER_PAGE]
        sections.append(f"### Page: {url}\n{truncated}\n")
    sections.append("\nExtract the company information from the pages above.")
    prompt = "\n".join(sections)
    return prompt + _RETRY_SUFFIX if retry else prompt


def _actual_missing_fields(result: _ExtractionResult) -> list[MissingField]:
    missing: list[MissingField] = []
    if not result.company_name:
        missing.append("company_name")
    if not result.value_proposition:
        missing.append("value_proposition")
    if not result.target_icp:
        missing.append("target_icp")
    if not result.pricing_tiers:
        missing.append("pricing_tiers")
    if not result.features:
        missing.append("features")
    return missing


def _confidence_from_missing(missing: list[MissingField], total_fields: int = 5) -> Literal["high", "medium", "low"]:
    if not missing:
        return "high"
    if len(missing) <= total_fields // 2:
        return "medium"
    return "low"


def _is_essentially_empty(result: _ExtractionResult) -> bool:
    return not result.value_proposition and not result.pricing_tiers and not result.features


def _to_profile(domain: str, pages: dict[str, str], result: _ExtractionResult) -> CompanyProfile:
    missing = _actual_missing_fields(result)
    return CompanyProfile(
        domain=domain,
        company_name=result.company_name,
        value_proposition=result.value_proposition,
        target_icp=result.target_icp,
        pricing_tiers=result.pricing_tiers,
        features=result.features,
        extracted_at=datetime.now(timezone.utc),
        source_pages=list(pages.keys()),
        extraction_confidence=_confidence_from_missing(missing),
        missing_fields=missing,
    )


def extract_company_profile(domain: str, pages: dict[str, str], llm: LLMClient) -> CompanyProfile:
    if not pages:
        return _to_profile(domain, pages, _ExtractionResult())

    result = llm.complete(system=_SYSTEM_PROMPT, prompt=_build_prompt(domain, pages), schema=_ExtractionResult)

    if _is_essentially_empty(result):
        # One retry with a more directive prompt before accepting an empty
        # result — the content genuinely exists (pages is non-empty), so an
        # empty result is more likely a model miss than a true absence.
        result = llm.complete(
            system=_SYSTEM_PROMPT, prompt=_build_prompt(domain, pages, retry=True), schema=_ExtractionResult
        )

    return _to_profile(domain, pages, result)
